apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hercules.isponsorblocktv.fullname" . }}
  labels:
    {{- include "hercules.labels" . | nindent 4 }}
data:
  config.json: |+
    {
      "devices": [
          {
              "screen_id": {{ .Values.isponsorblocktv.screenId | quote }},
              "name": "YouTube on TV",
              "offset": 0
          }
      ],
      "apikey": "",
      "skip_categories": [
          "sponsor",
          "selfpromo"
      ],
      "channel_whitelist": [],
      "skip_count_tracking": true,
      "mute_ads": true,
      "skip_ads": true,
      "auto_play": true
    }
