apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hercules.mosquitto.fullname" . }}
  labels:
    {{- include "hercules.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: hercules-mosquitto
      {{- include "hercules.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        app: hercules-mosquitto
        {{- include "hercules.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:1.6.15
        ports:
        - containerPort: 1883
        